---
title: "Nicole Kadosh"
---


411 Madison Ave, Apt. 106 
Boone, NC 28607

kadoshn@appstate.edu

954-892-4455

##Summary of Qualifications:
I will be a first generation college graduate from Appalachian State University. I am looking for a way to utilize my degree in Mathematics and concentration in Life Sciences. I am a quick study who pays attention to detail and am very task oriented, organized and hard working. I am an outgoing person and work well in groups, as either a leader or follower depending on what the situation needs.

##Education:

• Bachelor of Science in Mathematics, Concentration in Life Sciences at   Appalachian State University

##Skills: 

• Experience with programming languages R and Python

• Experience with Excel and Github

• Mathematical and Statictical Analysis

• Hard Worker and Dedicated


##Courses Related to Degree:

• Statistical Data Analysis

• Computational Mathematics

• Linear Algebra

• Mathematical Biology

• Data Science

##Experience:

• Boss Certified Realtime Reporting; Fort Lauderdale Florida
  Secretary; paper work, answering phones, time management and organization

• Six Pence Pub; Blowing Rock NC
  Hostess; greeting customers, organization skills and team work
  
• Cutco; Fort Lauderdale, Florida Branch
  Sales; customer service and task oriented
  
• JCC; Davie, Florida
  Camp Councelor; Responsibilites of children, organization and   leadership